Adding SFP entries for additional 10g ports
Azure/sonic-buildimage pull request #10039
Opened 2022-02-19 01:51 UTC by tjchadaga

#### Why I did it
Fixes https://github.com/Azure/sonic-buildimage/issues/10038

#### How I did it
Added SFP entries for additional 10G ports added in https://github.com/Azure/sonic-buildimage/pull/9988

#### How to verify it
Load image and validate xcvrd stays in RUNNING state

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [x] 202006
- [x] 202012
- [x] 202106
- [x] 202111

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2022-02-20 13:15 UTC, aravindmani-1 requested changes

2022-02-20 13:15 UTC, aravindmani-1 commented on device/dell/x86_64-dell_s6100_c2538-r0/platform.json
>              }
Looks like comma is missing here.

2022-02-20 13:15 UTC, aravindmani-1 commented on device/dell/x86_64-dell_s6100_c2538-r0/platform.json
> +            }
Looks like comma is missing here. Could you please check?.

2022-02-20 13:16 UTC, aravindmani-1 commented on device/dell/x86_64-dell_s6100_c2538-r0/platform.json
> +            }
Port 65 and 66 are SFP+ ports. Not QSFP+ ports.

2022-02-21 08:05 UTC, aravindmani-1 commented
From the crash logs, it is crashing while retrieving _sfp_list[]. The changes you made doesn't seems to be resolving the crash. Could you execute "docker exec -it pmon bash", python3 /usr/local/bin/xcvrd and check whether the crash is seen?.

2022-02-23 07:08 UTC, prgeor commented
@tjchadaga @aravindmani-1 can this be closed, now this [PR10062](https://github.com/Azure/sonic-buildimage/pull/10062) is raised.?

2022-02-28 21:15 UTC, tjchadaga commented
Since the issue is resolved with https://github.com/Azure/sonic-buildimage/pull/10062, closing this PR

2022-02-28 21:15 UTC, closed without merging