[202106] [Mellanox] Fix DPB supported breakout modes
Azure/sonic-buildimage pull request #10129
Opened 2022-03-02 09:56 UTC by alexrallen

**Cherry pick of https://github.com/Azure/sonic-buildimage/pull/10072**

#### Why I did it

Removing DPB breakout modes that require adjacent ports to be disabled as that is not supported by the current DPB infrastructure.

Correspondingly had to remove the `hwsku.json` file from any SKUs which utilized these removed modes such that the system will fall back to `ports_config.ini` and DPB will not be supported for those SKUs.

#### How I did it

Modified the `platform.json` files of Mellanox devices.

#### How to verify it

Execute `show int break [Ethernet]` on the affected platforms and ensure there are no modes present that would require an adjacent port to be disabled to function. 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111

#### Description for the changelog
[mellanox] Fix DPB supported breakout modes

#### A picture of a cute animal (not mandatory but encouraged)
![borzoi_body_image_2](https://user-images.githubusercontent.com/5898707/153689781-8d64724c-e9bc-476b-b84d-5c72d0d21648.jpg)

2022-03-02 09:57 UTC, alexrallen commented
@arlakshm Please find the cherry pick here.

2022-03-02 17:22 UTC, dgsudharsan approved these changes

2022-03-02 17:29 UTC, dgsudharsan requested changes

2022-03-02 17:29 UTC, dgsudharsan commented on device/mellanox/x86_64-mlnx_msn3800-r0/platform.json
> -                "1x10G[100G,50G,40G,25G]": ["etp1"],
Please have 1x10G in 202106 as the fix https://github.com/Azure/sonic-buildimage/pull/9278 is not present in 202106

2022-03-02 20:35 UTC, dgsudharsan commented
Please do not merge until https://github.com/Azure/sonic-buildimage/pull/9278 is merged

2022-03-10 11:48 UTC, liat-grozovik approved these changes

2022-03-24 20:57 UTC, dgsudharsan approved these changes

2022-03-27 06:15 UTC, merged