SONiC Yang model support for Kdump
Azure/sonic-buildimage pull request #10786
Opened 2022-05-09 17:48 UTC by rajendra-dendukuri

#### Why I did it
Created SONiC Yang model for Kdump
Tables: KDUMP

#### How I did it
Defined Yang models for NAT based on Guideline doc:
https://github.com/Azure/SONiC/blob/master/doc/mgmt/SONiC_YANG_Model_Guidelines.md
and
https://github.com/Azure/sonic-utilities/blob/master/doc/Command-Reference.md

#### How to verify it
Added test cases to verify it.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2022-05-09 20:25 UTC, arlakshm submitted a review, later dismissed

2022-05-09 23:29 UTC, ganglyu submitted a review, later dismissed

2022-05-10 20:06 UTC, dgsudharsan requested changes
Can you please add configuration schema in the document?

https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md

2022-05-10 20:25 UTC, dgsudharsan approved these changes

2022-05-10 21:00 UTC, qiluo-msft approved these changes

2022-05-11 06:25 UTC, merged