Revert "[arm] Refactor installer and build to allow arm builds targeted at grub platforms"
Azure/sonic-buildimage pull request #11599
Opened 2022-08-01 23:14 UTC by qiluo-msft

Reverts Azure/sonic-buildimage#11341

2022-08-01 23:19 UTC, qiluo-msft commented
@alexrallen Please help check. You may redo your original PR after this revert.

2022-08-01 23:21 UTC, xumia approved these changes

2022-08-01 23:54 UTC, alexrallen requested changes
What is the reasoning of this revert? The PR description fails to justify such a measure. 

1. I don't see how a revert is justified by non-functional code organization issues. While I would have preferred any issues with the file extensions / organization to be reported with the original PR I do not see how this could not be resolved by an additional PR on top of what already exists. 

2. Your second point refers to an issue that I am under the impression that is being resolved by another PR (https://github.com/Azure/sonic-buildimage/pull/11572) What additional issues exist that warrant a revert?

2022-08-02 01:52 UTC, qiluo-msft commented
Close this in favor of https://github.com/Azure/sonic-buildimage/pull/11572

2022-08-02 01:53 UTC, closed without merging