YANG sonic-interface: add missing mac_addr leaf
Azure/sonic-buildimage pull request #20968
Opened 2024-11-29 13:34 UTC by bradh352

#### Why I did it

YANG configuration verification fails during `config replace`.

#### How I did it

mac_addr support was added in the INTERFACES table by https://github.com/sonic-net/sonic-swss/pull/814 in 2020 but the YANG models were never updated to reflect that change.  Updated yang model to reflect change.

#### How to verify it

Add mac_addr to INTERFACE table then run `config replace` and it succeeds.

Signed-off-by: Brad House (@bradh352)

##### Work item tracking

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [X] 202006
- [X] 202012
- [X] 202106
- [X] 202111
- [X] 202205
- [X] 202211
- [X] 202305

Marked all releases that contained the change.

#### Tested branch (Please provide the tested image version)

master as of 20241109

#### Description for the changelog

YANG INTERFACE: add missing mac_addr leaf

#### Link to config_db schema for YANG module changes

There is no actual INTERFACE section in the docs (there probably should be).

#### A picture of a cute animal (not mandatory but encouraged)

2024-11-30 00:27 UTC, bradh352 commented
test failures are unrelated to this PR

2024-11-30 00:35 UTC, bradh352 commented
/AzurePipelines run Azure.sonic-buildimage

2024-12-06 00:25 UTC, dgsudharsan requested changes
Can you please add this config to sample_config_db.json as well us update the schema in Configuration.md?
In addition can you please add a test case covering MAC address with capital hex letters to see if it pass?

2024-12-06 00:58 UTC, bradh352 commented
@dgsudharsan I guess I'll need to break out an INTERFACE section since such a thing doesn't exist in the current docs and try to migrate the other info into there.

2024-12-06 01:57 UTC, bradh352 commented
@dgsudharsan ready for review

2024-12-06 02:04 UTC, dgsudharsan commented
@bradh352 I think there is some problem with the diff in configuration.md. Due to formatting, it is showing a huge diff which will be very hard to manage especially when we plan to cherry-pick changes to different branches. Can you please ensure the diff shows only the changed content?

2024-12-06 02:06 UTC, bradh352 commented
@dgsudharsan  I thought you might say that.  I'm really frustrated with the markdown format used (inconsistently and incorrectly) in that doc, so I fixed a lot of it.  It was worth a shot to clean it up and actually make, say, the Table of Contents links actually work.  Oh well.  I'll revert that stuff and just keep the changes relevant to this PR.

2024-12-06 02:22 UTC, bradh352 commented
@dgsudharsan hopefully that's acceptable now, please review

2024-12-06 13:09 UTC, bradh352 commented
found a couple minor bugs, one unexpected as I didn't realize the double-conversion flow for the sample db. those should be corrected now.

2024-12-06 13:34 UTC, bradh352 commented
@dgsudharsan I moved the most important parts of my markdown cleanup into PR #21072 it would be great if that could be merged.  I provided the links to render mine vs original, you'll see the table of contents works on mine.

2024-12-09 03:44 UTC, dgsudharsan approved these changes

2024-12-11 21:44 UTC, bradh352 commented
rebased to force rebuild to see if build general sonic CI build/test issues have been resolved

2024-12-13 13:57 UTC, bradh352 commented
@dgsudharsan @qiluo-msft please merge

2024-12-15 19:49 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-15 19:49 UTC, bradh352 commented
rebased to try to force rebuild since last build hung

2024-12-16 01:12 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-16 01:13 UTC, bradh352 commented
rebased for merge conflict after PR #21072

2024-12-16 01:19 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-17 01:56 UTC, bradh352 commented
@qiluo-msft please approve and merge

2024-12-19 12:35 UTC, bradh352 commented
@qiluo-msft @dgsudharsan what's the status of merging this?  seems pretty trivial at this point.  All tests requested were added, everything is passing.

2024-12-19 16:44 UTC, dgsudharsan commented
@bradh352  I don't have merge permissions. It should be @qiluo-msft  or @lguohan

2024-12-24 12:59 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-24 12:59 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2024-12-24 13:08 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2025-01-08 12:11 UTC, bradh352 commented
rebased against master to force rebuild...

2025-01-08 12:12 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2025-01-09 13:14 UTC, bradh352 commented
@qiluo-msft @lguohan please merge this trivial yang fix

2025-01-13 13:01 UTC, bradh352 commented
@qiluo-msft please merge

2025-02-05 02:20 UTC, ganglyu approved these changes
LGTM
@prsunny Could you please review this PR? Do we really need the MAC address?

2025-02-05 02:27 UTC, bradh352 commented
@ganglyu

> LGTM @prsunny Could you please review this PR? Do we really need the MAC address?

This isn't adding a feature for mac addresses, just letting YANG know about something that already exists.

Also, the use case for setting mac addresses is for pure layer3 environments (e.g. VXLAN EVPN - BGP).  If you have 2 switches wired together with dual ports (for redundancy), you need each port to have a different mac address otherwise you have mac conflicts.  At least on my Trident3 switches, every port defaults to the same system-wide mac address. So it is necessary.

2025-02-05 04:09 UTC, wen587 commented
Is it good to support from now for mac_address? Do we need to backport? It will break YANG validation if we add mac_address in INTERFACE for the past releases.

2025-02-05 10:49 UTC, bradh352 commented
@wen587 

> Is it good to support from now for mac_address? Do we need to backport? It will break YANG validation if we add mac_address in INTERFACE for the past releases.

not sure how it would break yang validation, if someone is using mac_addr currently they aren't doing any yang validation at all since yang would reject.  But I don't honestly care if its backported or not.

2025-02-05 23:58 UTC, prsunny commented on src/sonic-yang-models/yang-models/sonic-vlan.yang
> +				leaf mac_addr {
this is an optional field.

2025-02-06 00:02 UTC, bradh352 commented on src/sonic-yang-models/yang-models/sonic-vlan.yang
> +				leaf mac_addr {
This doesn't have the `mandatory true;` attribute and also doesn't have a default value .... so it is therefore optional as far as I am aware.

What am I missing here?

2025-02-06 00:47 UTC, wen587 approved these changes

2025-02-21 01:51 UTC, qiluo-msft approved these changes

2025-02-21 01:57 UTC, mssonicbld commented
/azp run Azure.sonic-buildimage

2025-02-21 22:31 UTC, prsunny approved these changes

2025-02-23 19:59 UTC, bradh352 commented
thanks for the approvals, can this be merged now?

2025-03-08 20:21 UTC, bradh352 commented
@prsunny, @ganglyu, @qiluo-msft since this has a bunch of approvals, can it be merged please?

2025-03-09 17:49 UTC, merged

2026-06-16 20:10 UTC, BYGX-wcr commented
@r12f , need to cherry-pick this to 202412 and 202511