Platform Driver Developement Framework (PDDF)
Azure/sonic-buildimage pull request #4756
Opened 2020-06-11 10:04 UTC by fk410167

Signed-off-by: Fuzail Khan <fuzail.khan@broadcom.com>

This change introduces PDDF which is described here,
https://github.com/Azure/SONiC/pull/536

Most of the platform bring up effort goes in developing the platform device drivers, SONiC platform APIs and validating them. Typically each platform vendor writes their own drivers and platform APIs which is very tailor made to that platform. This involves writing code, building, installing it on the target platform devices and testing. Many of the details of the platform are hard coded into these drivers, from the HW spec. They go through this cycle repetitively till everything works fine, and is validated before upstreaming the code.
PDDF aims to make this platform driver and platform APIs development process much simpler by providing a data driven development framework. This is enabled by:

JSON descriptor files for platform data
Generic data-driven drivers for various devices
Generic SONiC platform APIs
Vendor specific extensions for customisation and extensibility

**- Why I did it**
Rapid development and qualification of different platforms on SONiC OS.

**- How I did it**
PDDF generic platform drivers and utils are provided under
sonic-buildimage/platform/pddf/i2c/

PDDF generic user space 2.0 platform APIs are added here,
sonic-buildimage/platform/pddf/platform-api-pddf-base/

Rest of the changes are added to enable the framework.

**- How to verify it**
We will add support for a sample platform to enable verification.

Under PDDF mode, pddf utils can be verified,
# sudo pddf_psuutil <options>
# sudo pddf_fanutil <options>
# sudo pddf_thermalutil <options>
# sudo pddf_ledutil <options>

**- Description for the changelog**

Platform Driver Development Framework (PDDF): Generic kernel device drivers and platform APIs

**- A picture of a cute animal (not mandatory but encouraged)**

Depends on:
https://github.com/Azure/sonic-platform-common/pull/92
https://github.com/Azure/sonic-utilities/pull/940

2020-08-10 00:44 UTC, fk410167 commented on platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_chassis.py
> +        self.sys_eeprom = Eeprom(self.pddf_obj, self.plugin_data)
lgtm[py/call/wrong-number-class-arguments]

2020-08-10 00:44 UTC, fk410167 commented on platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_chassis.py
> +                fan = Fan(i, j, self.pddf_obj, self.plugin_data)
lgtm[py/call/wrong-number-class-arguments]

2020-08-10 00:44 UTC, fk410167 commented on platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_chassis.py
> +            psu = Psu(i, self.pddf_obj, self.plugin_data)
lgtm[py/call/wrong-number-class-arguments]

2020-08-10 00:44 UTC, fk410167 commented on platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_chassis.py
> +            sfp = Sfp(index, self.pddf_obj, self.plugin_data)
lgtm[py/call/wrong-number-class-arguments]

2020-08-10 00:45 UTC, fk410167 commented on platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_chassis.py
> +            thermal = Thermal(i, self.pddf_obj, self.plugin_data)
lgtm[py/call/wrong-number-class-arguments]

2020-08-10 00:45 UTC, fk410167 commented on platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_platform.py
> +        self._chassis = Chassis(self.pddf_data, self.pddf_plugin_data)
lgtm[py/call/wrong-number-class-arguments]

2020-08-10 00:46 UTC, fk410167 commented on platform/pddf/platform-api-pddf-base/sonic_platform_pddf_base/pddf_psu.py
> +            psu_fan = Fan(0, psu_fan_idx, pddf_data, pddf_plugin_data, True, self.psu_index)
lgtm[py/call/wrong-number-class-arguments]

2020-08-10 00:47 UTC, fk410167 commented
Added comment
"lgtm[py/call/wrong-number-class-arguments]"
on various lines to ignore this specific alert as they are not correct.

2020-08-11 12:54 UTC, fk410167 commented
retest vsimage

2020-08-11 13:07 UTC, fk410167 commented
retest vsimage please

2020-08-12 14:34 UTC, fk410167 commented
Need to ignore the 7 LGTM errors.

These errors are flagged because LGTM is trying to match platform classes developed outside of the PDDF framework with the expectations of the framework, which is not really valid.

2020-09-04 13:51 UTC, ben-gale commented
@jleveque - can we get this one merged please?

2020-09-16 18:34 UTC, ben-gale commented
> @jleveque - can we get this one merged please?

@jleveque - Joe?

2020-09-16 19:00 UTC, jleveque requested changes
As comments. Also, please resolve the conflict. Also suggest running all Python files through a tool such as autopep8 (e.g., `autopep8 --max-line-length 120`) to unify code style.

2020-10-16 15:15 UTC, fk410167 commented
@jleveque - I took care of your comments. Can you review?

2020-11-06 07:57 UTC, fk410167 commented
retest vsimage please

2020-11-08 04:31 UTC, fk410167 commented
retest vsimage, vs, broadcom please

2020-11-09 03:03 UTC, fk410167 commented
retest broadcom please

2020-11-09 11:36 UTC, fk410167 commented
retest vs please

2020-11-10 03:59 UTC, fk410167 commented
restest vsimage

2020-11-10 04:46 UTC, fk410167 commented
restest vsimage please

2020-11-10 05:00 UTC, fk410167 commented
restest vsimage please

2020-11-10 05:01 UTC, fk410167 commented
@jleveque 
Can you review this please?

2020-11-10 09:58 UTC, fk410167 commented
retest vsimage please

2020-11-12 18:22 UTC, jleveque approved these changes

2020-11-12 18:22 UTC, merged