[Mellanox] Always restart thermalctld on Mellanox platform when it exits
Azure/sonic-buildimage pull request #5375
Opened 2020-09-15 06:18 UTC by Junchao-Mellanox

**- Why I did it**

On mellanox paltform, part of thermalctld function is to handle user space thermal policies for events like fan/PSU removing, it works together with kernel thermal algorithm to make sure the switch won't be overheat.

Recently, we found that commit https://github.com/Azure/sonic-buildimage/commit/cbc75fe4c85fd01aded0bacb283c8bbf62adf2f8 changes its autorestart configuration in supervisord, and it won't be auto restarted after being killed. This PR is to make sure that thermalctld will be always restarted on mellanox platform when it is killed.

**- How I did it**

1. Add a variable "always_restart_thermalctld" in pmon_daemon_control.json
2. In docker-pmon.supervisord.conf.j2, it checks variable "always_restart_thermalctld" and set autorestart configuration for thermalctld accordingly.

**- How to verify it**

Manual test

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2020-09-15 07:22 UTC, jleveque commented
What is wrong with `autorestart=unexpected`? Under what circumstances the daemon will exit "expectedly" according to supervisor and thus not get restarted?

2020-09-15 07:25 UTC, Junchao-Mellanox commented
For example, user issue an kill command in pmon docker, it will send a terminate signal to thermalctld, thermalctld handls such signal and will clear all resources and exit with code 0. This won't trigger an auto restart.

2020-09-15 07:28 UTC, jleveque commented
> For example, user issue an kill command in pmon docker, it will send a terminate signal to thermalctld, thermalctld handls such signal and will clear all resources and exit with code 0. This won't trigger an auto restart.

Certainly, this makes sense. However, this is not "normal operation". If we are this concerned, then I would prefer reverting back to the previous solution (i.e., not creating a new variable/option -- make it `autorestart=true` always. However, I must ask, if we are concerned about user error, what would prevent a user from stopping the PMon container altogether?

2020-09-15 07:36 UTC, Junchao-Mellanox commented
Actually, we have regression test case which will kill thermalctld and wait for it to auto restart, and this case failed on master. We can also change the test case.

2020-09-16 03:29 UTC, jleveque requested changes
I prefer not introducing a new variable here. We should decide on a universal solution.

2020-09-16 04:16 UTC, Junchao-Mellanox commented
How about we put a exit(-1) to the end of thermalctld?

2020-09-16 04:31 UTC, jleveque commented
> How about we put a exit(-1) to the end of thermalctld?

As long as we have a non-zero exit code at every exit path, there should be no problem. FYI, exit codes in Linux are non-negative short integers, so `-1` will get converted to `255`. Prefer using a positive value so that it's easy to track down.

2020-09-18 03:50 UTC, Junchao-Mellanox commented
@jleveque Could you please take a look at https://github.com/Azure/sonic-platform-daemons/pull/94? With this new PR, we can drop the current PR.

2020-09-18 04:28 UTC, jleveque commented
Closing in favor of https://github.com/Azure/sonic-platform-daemons/pull/94

2020-09-18 04:28 UTC, closed without merging