[as4630-54pe]Modify to read correct psu SN and ID
Azure/sonic-buildimage pull request #5389
Opened 2020-09-16 08:31 UTC by jostar-yang

**- Why I did it**
The PSU is specific. Get SN and ID is not meet with standard method.
Old code
# cat psu_serial_number
SB020X18195100004
(It lack the last one byte. It should be SB020X181951000046 )
as4630-54pe-2:/sys/bus/i2c/drivers/as4630_54pe_psu/11-0051# cat psu_model_name
YPEB1200?AM-1A03P10 ( It should beYPEB1200?AM )
**- How I did it**
Modift psu drv to get and parse/shift need offset to get correct data
**- How to verify it**
New Code
# cat psu_serial_number
SB020X181951000046

4630-54pe-2:/sys/bus/i2c/drivers/as4630_54pe_psu/11-0051# cat psu_serial_number
SB020X181951000047

as4630-54pe-2:/sys/bus/i2c/drivers/as4630_54pe_psu/11-0051# cat psu_model_name
YPEB1200AM
as4630-54pe-2:/sys/bus/i2c/drivers/as4630_54pe_psu/11-0051#
as4630-54pe-2:/sys/bus/i2c/drivers/as4630_54pe_psu/11-0051#
4630-54pe-2:/sys/bus/i2c/drivers/as4630_54pe_psu/11-0051# cat psu_serial_name
SB020X181951000047
as4630-54pe-2:/sys/bus/i2c/drivers/as4630_54pe_psu/10-0050# cat psu_model_name
YPEB1200AM
**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [x] 201911
- [x] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2020-09-16 18:31 UTC, jleveque requested changes

2020-09-16 18:31 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-accton/as4630-54pe/modules/x86-64-accton-as4630-54pe-psu.c
> +        }
These lines are not aligned. Need to be indented 4 more spaces.

2020-09-17 15:54 UTC, jleveque commented
Retest mellanox please

2020-09-17 15:54 UTC, jleveque commented
Retest vsimage please

2020-09-17 15:54 UTC, jleveque submitted a review, later dismissed

2020-09-27 17:22 UTC, lguohan commented
Retest vsimage please

2020-09-27 17:22 UTC, lguohan commented
Retest mellanox please

2021-01-25 00:36 UTC, lguohan commented
/AzurePipeline run

2021-01-29 06:34 UTC, jostar-yang commented
Retest vsimage please

2021-07-08 01:35 UTC, jostar-yang commented
Can you merge code?　This PR  pass all checking for a long time.

2021-07-24 23:43 UTC, lguohan approved these changes

2021-07-24 23:45 UTC, merged