[Mellanox] Skip pcied on mellanox platform
Azure/sonic-buildimage pull request #5471
Opened 2020-09-27 07:25 UTC by Junchao-Mellanox

**- Why I did it**

pcied is not supported on mellanox platform and may cause regression failure.

**- How I did it**

Skip pcied in pmon_daemon_control.json

**- How to verify it**

Manual test

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2020-10-01 06:24 UTC, lguohan commented
please supply data to support pcied.

2020-10-02 09:32 UTC, lguohan requested changes
i do not think we should skip, instead we should add needed data to enable the check.

2020-10-04 14:02 UTC, liat-grozovik commented
@lguohan as this is new req which is not yet supported and should be added to all Mellanox switches we should skip it for now and once we deliver the info for all supported platforms we should enable it again.

2020-10-08 01:04 UTC, sujinmkang commented
@Junchao-Mellanox Since the pcie configuration file is not located in the expected platform directory, then pcied will just exit. Did you see any problem with the pcied?

2020-10-09 01:37 UTC, Junchao-Mellanox commented
> @Junchao-Mellanox Since the pcie configuration file is not located in the expected platform directory, then pcied will just exit. Did you see any problem with the pcied?

It fails the reboot test due to check_pmon_daemon_status report that pcied is not there.

2020-10-13 10:36 UTC, Junchao-Mellanox commented
Close as Kebo will add a configuration file for pcied.

2020-10-13 10:36 UTC, closed without merging