[docker-base]: Rate limit priority INFO and lower in syslog
Azure/sonic-buildimage pull request #5666
Opened 2020-10-19 19:15 UTC by theasianpianist

Signed-off-by: Lawrence Lee <lawlee@microsoft.com>

**- Why I did it**
There is currently a bug where messages from swss with priority lower than the current log level are still being counted against the syslog rate limiting threshhold. This leads to rate-limiting in syslog when the rate-limiting conditions have not been met, which causes several sonic-mgmt tests to fail since they are dependent on LogAnalyzer. It also omits potentially useful information from the syslog. Only rate-limiting messages of level INFO and lower allows these tests to pass successfully.

**- How I did it**
Add `$SystemLogRateLimitSeverity` option to `rsyslog.conf` in the base Dockerfiles

**- How to verify it**
Build a new orchagent image and install it. Run the ACL tests, which should now pass. No rate limiting should occur in the syslogs.

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2020-10-19 19:21 UTC, jleveque requested changes
Can you also please update the related comments to read:

```
# Set a rate limit on messages from the container of INFO level (level 6) or lower
```

2020-10-19 19:24 UTC, jleveque commented
You may also want to make the same change here: files/image_config/rsyslog/rsyslog-container.conf.j2

2020-10-19 20:44 UTC, jleveque approved these changes

2020-10-20 00:39 UTC, lguohan approved these changes

2020-10-20 18:52 UTC, merged