[minigraph.py]: Add support for parsing mux cable
Azure/sonic-buildimage pull request #5676
Opened 2020-10-20 18:51 UTC by theasianpianist

Signed-off-by: Lawrence Lee <lawlee@microsoft.com>

**- Why I did it**

**- How I did it**
Find LogicalLinks in minigraph and parse the port information. A new field called `mux_cable_connection` is added to each port's entry in the Port table in config DB:

```
PORT|Ethernet0: {
	"alias": "Ethernet4/1"
	...
	"mux_cable_connection": "u"
}
```

The default is to set this to "none" for ports that are not connected to a mux cable, rather than omitting it entirely.

If the port is connected to a smart cable, this field will take the value of the `<StartPort>` from the minigraph. 

**- How to verify it**
Run sonic-config-engine minigraph tests

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2020-10-20 21:19 UTC, jleveque requested changes

2020-10-20 21:19 UTC, jleveque commented on src/sonic-config-engine/tests/test_minigraph_case.py
> +                self.assertTrue("mux_cable_connection" not in port)
Add newline at EOF

2020-10-21 08:02 UTC, lguohan commented
do we need to differentiate U and L for a mux cable port? what is the motivation here?

2020-10-21 17:14 UTC, theasianpianist commented
@lguohan the minigraph will list the `<StartPort>` as either U or L to distinguish the upper and lower ToRs. We can change this field to true/false and move upper/lower ToR info to somewhere else if necessary.

@vdahiya12 for visibility

2020-10-21 17:31 UTC, theasianpianist commented
retest broadcom please

2020-10-22 02:51 UTC, vdahiya12 commented
> @lguohan the minigraph will list the `<StartPort>` as either U or L to distinguish the upper and lower ToRs. We can change this field to true/false and move upper/lower ToR info to somewhere else if necessary.
> 
> @vdahiya12 for visibility

@lguohan Can the Cli request to change the active TOR to be U or L, if not we can omit this ?

2020-10-23 05:23 UTC, vdahiya12 approved these changes

2020-10-23 19:37 UTC, jleveque approved these changes

2020-10-24 19:37 UTC, lguohan commented
retest vsimage please

2020-10-26 02:31 UTC, vdahiya12 approved these changes

2020-10-26 05:36 UTC, lguohan approved these changes

2020-10-26 15:52 UTC, merged