Add the vtysh command with newly added "-n"  option for multi asic  to  the read_only_cmds
Azure/sonic-buildimage pull request #5845
Opened 2020-11-06 20:32 UTC by arlakshm

Signed-off-by: Arvindsrinivasan Lakshmi Narasimhan <arlakshm@microsoft.com>

**- Why I did it**
In multi asic platforms the "show ip bgp summary" commands is not available for user with read only privileges, so fix this the vtysh command with the new` "-n"` option, added for multi asic platforms, needs to be added to the READ_ONLY_COMMANDS list in the sudoers files 

**- How I did it**
Add the command `vtysh -n [0-9] -c show *` to list of READ_ONLY_COMMANDS in the sudoers files

**- How to verify it**
Verify show ip bgp summary is working for user accounts with read-only privilages

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [X ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2020-11-06 20:37 UTC, jleveque requested changes

2020-11-06 20:37 UTC, jleveque commented on files/image_config/sudoers/sudoers
> +                                 /usr/bin/vtysh -c show *, /usr/bin/vtysh -n [0-9] -c show *, \
Suggest moving to its own line

2020-11-06 23:52 UTC, arlakshm commented on files/image_config/sudoers/sudoers
> +                                 /usr/bin/vtysh -c show *, /usr/bin/vtysh -n [0-9] -c show *, \
Moved to a new line

2020-11-07 00:07 UTC, jleveque approved these changes

2020-11-10 20:18 UTC, merged