[reboot-history] Add reboot history to state db
Azure/sonic-buildimage pull request #5933
Opened 2020-11-16 18:25 UTC by sujinmkang

**- Why I did it**
Add reboot history to State db so that can be used telemetry service
**- How I did it**
Split the process-reboot-cause service to determine-reboot-cause and process-reboot-cause 
determine-reboot-cause to determine the reboot cause
process-reboot-cause to parse the reboot cause files and put the reboot history to state db
Moved to sonic-host-service* packages
**- How to verify it**
Performed unit test and tested on DUT
**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2020-11-19 17:43 UTC, sujinmkang commented
retest vsimage please

2020-11-19 19:12 UTC, jleveque requested changes

2020-11-19 19:12 UTC, jleveque commented on src/sonic-host-services/scripts/process-reboot-cause
> +    REBOOT_FILE_LIST = [os.path.join(REBOOT_CAUSE_HISTORY_DIR,i) for i in os.listdir(REBOOT_CAUSE_HISTORY_DIR)]
Add space after comma

2020-11-19 19:12 UTC, jleveque commented on src/sonic-host-services/scripts/process-reboot-cause
> +    for i in range(min(10,len(TIME_SORTED_FULL_REBOOT_FILE_LIST))):
Add space after comma

2020-11-19 19:12 UTC, jleveque commented on src/sonic-host-services/setup.py
> +]
`dependencies` is not being used. Please remove this and add these dependencies to the `install_requires` list below instead. Also, it doesn't look like `natsort` is being used and the other two dependencies are already there.

2020-11-20 01:50 UTC, jleveque approved these changes

2020-11-20 02:06 UTC, jleveque requested changes
Please fix LGTM alert.

2020-11-20 06:31 UTC, jleveque approved these changes

2020-11-20 17:23 UTC, sujinmkang commented
retest vsimage please

2020-11-21 04:08 UTC, merged