Remove swss/syncd/teamd from Feature Table.
Azure/sonic-buildimage pull request #6000
Opened 2020-11-23 07:29 UTC by abdosi

Why I did:

As mention in Issue#https://github.com/Azure/sonic-buildimage/issues/5999
since we have dependency among swss/syncd/teamd removed from feature table as of now

How I did:

- Removed swss/syncd/teamd from Feature table handling

- Made Container  Auto restart as default enable for feature if not exist in Feature Table

How I Verify:

a) Made sure auto-restart works fine for swss/syncd/teamd

2020-11-23 16:53 UTC, abdosi commented
vsimage test "test_po_cleanup.py" failure is expected since we need to update the test case based on this change.
In the test case we are using config feature teamd disabled which will not work after this change.

2020-11-24 07:22 UTC, rlhui approved these changes

2020-11-25 01:25 UTC, jleveque requested changes
As comments.

Also please update PR title and description to align with new solution.

2020-11-25 01:25 UTC, jleveque commented on files/scripts/supervisor-proc-exit-listener
> +            if ((restart_feature != 'disabled') and expected == 0 and
Extra parentheses are no longer needed around `restart_feature != 'disabled'`

2020-11-25 01:45 UTC, abdosi commented on files/scripts/supervisor-proc-exit-listener
> +            if ((restart_feature != 'disabled') and expected == 0 and
@jleveque Updated

2020-11-25 01:50 UTC, jleveque approved these changes

2020-11-25 16:41 UTC, merged