[relay]: Prevent Buffer Overrun Of Malformed DHCP Packet
Azure/sonic-buildimage pull request #6057
Opened 2020-11-29 00:39 UTC by tahmed-dev

The add/strip relay agent options do not take into account the buffer
length and so it is possible to overrun the buffer. The issue will
result in contents from previous packet being aded to the current one.

signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>

**- Why I did it**

**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2020-12-01 02:29 UTC, jleveque requested changes

2020-12-01 02:29 UTC, jleveque commented on src/isc-dhcp/patch/0009-relay-Prevent-Buffer-Overrun.patch
> +result in contents from previous packet being aded to the current one.
Typo: s/aded/added/

2020-12-02 16:43 UTC, tahmed-dev commented
retest mellanox please

2020-12-07 14:21 UTC, tahmed-dev commented
retest mellanox please

2020-12-10 17:56 UTC, tahmed-dev commented
retest this please

2020-12-10 23:00 UTC, jleveque approved these changes
LGTM. Should this patch be upstreamed?

2020-12-11 00:01 UTC, tahmed-dev commented
> LGTM. Should this patch be upstreamed?

I guess so. There could be cross packets information leak.

2020-12-11 00:05 UTC, trzhang-msft approved these changes

2020-12-12 00:28 UTC, merged