[Mellanox] Add python3 support for Mellanox platform API
Azure/sonic-buildimage pull request #6175
Opened 2020-12-10 08:23 UTC by Junchao-Mellanox

**- Why I did it**

python2 is end of life and SONiC is going to support python3. This PR is going to support:

1. Mellanox SONiC platform API python3 support
2. Install both python2 and python3 verson of Mellanox SONiC platform API or pmon and host side

**- How I did it**

1. Change docker-platform-monitor make files to install both python2 and python3 whl
2. Change Mellanox SONiC platform API code to support both python2 and python3

**- How to verify it**

Run platform regressions on a few platforms

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2020-12-10 23:29 UTC, jleveque requested changes

2020-12-10 23:29 UTC, jleveque commented on files/build_templates/sonic_debian_extension.j2
> +MLNX_PLATFORM_COMMON_PY3_WHEEL_NAME=$(basename {{mlnx_platform_api_py3_wheel_path}})
Nomenclature nit-pick: The vendor-implemented API package is simply called "sonic-platform", not "sonic-platform-common". The base API package is called "sonic-platform-common". I suggest you change "mlnx-sonic-platform-common" to "mlnx-sonic-platform" and "MLNX_PLATFORM_COMMON_PY3_WHEEL_NAME" to "MLNX_SONIC_PLATFORM_PY3_WHEEL_NAME". Also suggest doing the same for the Python 2 package above.

2020-12-10 23:29 UTC, jleveque commented on rules/docker-platform-monitor.mk
> +$(DOCKER_PLATFORM_MONITOR)_PYTHON_WHEELS += $(SONIC_PLATFORM_API_PY3)
Suggest moving this under line 16 to keep next to the Py2 version.

2020-12-10 23:29 UTC, jleveque commented
@Junchao-Mellanox: Once this PR is merged, are we good to merge https://github.com/Azure/sonic-buildimage/pull/5886?

2020-12-11 02:00 UTC, Junchao-Mellanox commented
> @Junchao-Mellanox: Once this PR is merged, are we good to merge #5886?

@keboliu I suppose you are working on the system health python3 migration, could you answer this comment?

2020-12-11 03:42 UTC, jleveque requested changes

2020-12-11 03:42 UTC, jleveque commented on platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py
> +    import builtins as exceptions
I believe you can remove this altogether. Please verify.

2020-12-11 03:42 UTC, jleveque commented on platform/mellanox/mlnx-platform-api/sonic_platform/eeprom.py
> +    import exceptions
I believe you can remove this altogether. Please verify.

2020-12-11 03:48 UTC, jleveque approved these changes

2020-12-11 10:59 UTC, keboliu commented
> > @Junchao-Mellanox: Once this PR is merged, are we good to merge #5886?
> 
> @keboliu I suppose you are working on the system health python3 migration, could you answer this comment?

generally, system-health has a dependency on platform API python3 lib, and when it ready system-health should be able to run, however, I see that system-health itself still has some issue in terms of string handling. left comments in another PR https://github.com/Azure/sonic-buildimage/pull/5886

2020-12-11 18:51 UTC, merged