[sysctl] Increase hung_task_timeout_secs to 300
Azure/sonic-buildimage pull request #6312
Opened 2020-12-29 02:02 UTC by daall

Depending on the performance characteristics of a given hardware platform,
it's possible to exceed the default 120 second kernel timeout during I/O
intensive operations like image installation. This risk increases as image
size continues to increase. So, we need to increase the timeout so that we
don't encounter kernel panics on devices with lower disk throughput.

Signed-off-by: Danny Allen <daall@microsoft.com>

2020-12-29 02:08 UTC, jleveque approved these changes

2020-12-29 02:34 UTC, yxieca approved these changes

2020-12-29 03:30 UTC, lguohan commented
i feel we should not change the default value here. instead, we should nice the installer. if kernel is in such bad state, the user space application might hang as well, hardware watchdog might timeout and reboot the box.

2020-12-29 03:30 UTC, lguohan requested changes
as comments

2020-12-29 03:57 UTC, yxieca commented
> i feel we should not change the default value here. instead, we should nice the installer. if kernel is in such bad state, the user space application might hang as well, hardware watchdog might timeout and reboot the box.

I think the issue is that the kernel takes too much time to flush IO to the hard drive. I am not sure if nice the use application would help. Unless we throttle the amount of data writing to the hard drive. Even that, because there is cache in between, we don't know when the kernel will flush how much data to hard drive. So I think we don't have control over this issue in user space.

2020-12-30 00:06 UTC, lguohan approved these changes
can you add more context for this change, so that later when we trace back to this pr, we know exactly why we made this change.

2020-12-30 00:12 UTC, daall commented
retest vsimage please

2020-12-30 13:00 UTC, merged