DellEMC Z9332f platform system health
Azure/sonic-buildimage pull request #6642
Opened 2021-02-02 09:47 UTC by aravindmani-1

**- Why I did it**

- Added support for platform system health daemon in Dell Z9332f platform. 

**- How I did it**

- Added the configuration, API changes to support system health

**- How to verify it**

- Execute "show system-health summary/detail/monitor-list" CLI.
- Check SYSTEM_HEALTH_INFO in stateDB.

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

**- Description for the changelog**
UT logs: 
[z9332f_system_health_UT.txt](https://github.com/Azure/sonic-buildimage/files/5910142/z9332f_system_health_UT.txt)

**- A picture of a cute animal (not mandatory but encouraged)**

2021-02-02 17:41 UTC, jleveque commented
Please fix conflicts

2021-02-03 04:54 UTC, aravindmani-1 commented
@jleveque Resolved the conflicts.

2021-02-03 19:32 UTC, jleveque requested changes

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/common/sonic_platform/hwaccess.py
> +    if(fd < 0):
Remove parentheses

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/common/sonic_platform/hwaccess.py
> +    if(os.lseek(fd, offset, os.SEEK_SET) != offset):
Remove parentheses

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/common/sonic_platform/hwaccess.py
> +    if(fd < 0):
Remove parentheses

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/common/sonic_platform/hwaccess.py
> +    if(os.lseek(fd, offset, os.SEEK_SET) != offset):
Remove parentheses

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/common/sonic_platform/hwaccess.py
> +    if(ret != 1):
Remove parentheses

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
> +        if(val != False):
Remove parentheses

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
> +        if(color == "green"):
Remove parentheses

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
> +        elif(color == "flash_green"):
Remove parentheses

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
> +        elif(color == "yellow"):
Remove parentheses

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
> +            if(not hwaccess.io_reg_write(self.io_res, self.sysled_offset, self.SYSTEM_LED_COLOR[color])):
Remove parentheses

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/psu.py
> +                             "Temperature": 0x3F } }
Fix alignment

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
> +            self.sys_ledcolor=color
Add spaces around `=`

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
> +            self.sys_ledcolor=color
Add spaces around `=`

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
> +            self.sys_ledcolor=color
Add spaces around `=`

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
> +                self.sys_ledcolor="green"
Add spaces around `=`

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
> +                self.sys_ledcolor="yellow"
Add spaces around `=`

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
> +                self.sys_ledcolor="flash_green"
Add spaces around `=`

2021-02-03 19:32 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-dell/z9332f/sonic_platform/chassis.py
> +                self.sys_ledcolor="flash_yellow"
Add spaces around `=`

2021-02-04 20:27 UTC, jleveque approved these changes

2021-02-06 21:53 UTC, merged