Fix Dell S6000 reboot issue
Azure/sonic-buildimage pull request #6688
Opened 2021-02-05 04:09 UTC by aravindmani-1

**- Why I did it**
Reboot command in Dell S6000 failed to reboot the switch.
**- How I did it**
Added retry mechanism and CPU reset.
**- How to verify it**
Execute reboot command in Dell S6000.
**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
[S6000_reboot_UT.txt](https://github.com/Azure/sonic-buildimage/files/5930031/S6000_reboot_UT.txt)

2021-02-11 06:11 UTC, aravindmani-1 commented
@sujinmkang , @jleveque can you please review this PR?.

2021-02-11 21:15 UTC, jleveque requested changes

2021-02-11 21:15 UTC, jleveque commented on device/dell/x86_64-dell_s6000_s1220-r0/platform_reboot
> +    if(fd < 0):
Parentheses unnecessary in Python. Please remove.

2021-02-11 21:15 UTC, jleveque commented on device/dell/x86_64-dell_s6000_s1220-r0/platform_reboot
> +    if(os.lseek(fd, offset, os.SEEK_SET) != offset):
Parentheses unnecessary in Python. Please remove.

2021-02-11 21:15 UTC, jleveque commented on device/dell/x86_64-dell_s6000_s1220-r0/platform_reboot
> +    if(ret != 1):
Parentheses unnecessary in Python. Please remove.

2021-02-16 23:37 UTC, jleveque approved these changes

2021-02-16 23:37 UTC, merged