[sonic-breakout_cfg.yang]: Remove yang model for BREAKOUT_CFG table.
Azure/sonic-buildimage pull request #6801
Opened 2021-02-17 02:25 UTC by praveen-li

Changes:
-- Remove yang model for BREAKOUT_CFG table. This table does not impact back-end
and also is verified already by using platform.json. So yang model is redundant.
-- Test case changes.

Signed-off-by: Praveen Chaudhary <pchaudhary@linkedin.com>

#### Why I did it

Changes:
-- Remove yang model for BREAKOUT_CFG table. This table does not impact back-end
and also is verified already by using platform.json. So yang model is redundant.

Keeping the yang model unnecessary forces the pattern and also will need to maintain it in future unnecessarily.

-- Test case changes.

#### How I did it

Remove the yang model and added the test case.
.
#### How to verify it

Built the packages after changing the tests.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

#### Description for the changelog

#### A picture of a cute animal (not mandatory but encouraged)

2021-02-23 21:42 UTC, kwangsuk commented
There is a reference to  BREAKOUT_CFG table and yang.
https://github.com/Azure/SONiC/blob/master/doc/dynamic-port-breakout/sonic-dynamic-port-breakout-HLD.md

Don't you need to update the HLD accordingly?

2021-02-23 21:57 UTC, praveen-li commented
Hi Kwan

There is no reference in HLD for breakout_cfg yang models. It's me know if you have seen it.
Note that the breakout table will still exist we are just removing the Yang model corresponding to it,

Thanks,

Regards
Praveen
________________________________
From: Kwan <notifications@github.com>
Sent: Tuesday, February 23, 2021 1:42 PM
To: Azure/sonic-buildimage <sonic-buildimage@noreply.github.com>
Cc: Praveen Chaudhary <pchaudhary@linkedin.com>; Author <author@noreply.github.com>
Subject: Re: [Azure/sonic-buildimage] [sonic-breakout_cfg.yang]: Remove yang model for BREAKOUT_CFG table. (#6801)


There is a reference to BREAKOUT_CFG table and yang.
https://github.com/Azure/SONiC/blob/master/doc/dynamic-port-breakout/sonic-dynamic-port-breakout-HLD.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FSONiC%2Fblob%2Fmaster%2Fdoc%2Fdynamic-port-breakout%2Fsonic-dynamic-port-breakout-HLD.md&data=04%7C01%7Cpchaudhary%40linkedin.com%7C5dc6f4258faa46fc1deb08d8d843f4a5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637497133667883360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=o7uBsp0OMrM8bjgyOAdpDEOQifpPNpBY1xL22VceV4s%3D&reserved=0>

Don't you need to update the HLD accordingly?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fsonic-buildimage%2Fpull%2F6801%23issuecomment-784532712&data=04%7C01%7Cpchaudhary%40linkedin.com%7C5dc6f4258faa46fc1deb08d8d843f4a5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637497133667883360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FuvzdOZeSsP9T8Lv0rzfY50jXbe80Rnp8d5%2FJxjuZfE%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJHZHPJLMO6RSOJ56UCVI5TTAQOM5ANCNFSM4XXQROKQ&data=04%7C01%7Cpchaudhary%40linkedin.com%7C5dc6f4258faa46fc1deb08d8d843f4a5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637497133667893317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Guz2TIGNPZuJnZCpu%2BBzmlpLGwPmPQ5hMpu4TkC9HGA%3D&reserved=0>.

2021-02-23 22:04 UTC, kwangsuk commented
@praveen-li 
Oh, ok. So, the BREAKOUT_CFG table will still exist. Then any reason to remove YANG file?

2021-03-05 20:14 UTC, praveen-li commented
> @praveen-li
> Oh, ok. So, the BREAKOUT_CFG table will still exist. Then any reason to remove YANG file?

Possible breakout modes are controlled by platform.json and are thoroughly checked by the Python code. So we do not need extra layer of checking using Yang model because then we have to maintain it at 2 places.

Also breakout CFG table doesn't impact backend.

2021-03-05 20:17 UTC, praveen-li commented
/Azure.sonic-buildimage run

2021-03-05 20:18 UTC, praveen-li commented
/Azure Pipelines/Azure.sonic-buildimage run

2021-03-11 18:12 UTC, anshuv-mfst commented
3/11: PR reviewed in YANG subgroup. 
@zhenggen-xu - could you please review as well.

2021-03-28 08:00 UTC, lguohan commented
@praveen-li, who to sign off?

2021-03-29 05:34 UTC, praveen-li commented
> @praveen-li, who to sign off?

@lguohan I think Xu can review this one, once I resolve the conflicts.
@zhenggen-xu

2021-04-06 03:03 UTC, Prasanth-KV submitted a review, later dismissed

2021-05-12 19:36 UTC, zhenggen-xu commented
After some more thought, I think we don't want to treat this table BREAKOUT_CFG very differently.  The main problem for this table with Yang models is that the breakout mode is not known for all platforms and hard to maintain.  Maybe we can relax that in the Yang model file, and we validate that by the sonic-utilities or other plugins (which was the case already).  The yang model here is still good to have at least to validate the sanity of field name etc. This also makes the table to be consistent with other tables.

2021-05-12 19:37 UTC, zhenggen-xu requested changes
As requested

2021-05-13 00:28 UTC, praveen-li commented
> After some more thought, I think we don't want to treat this table BREAKOUT_CFG very differently. The main problem for this table with Yang models is that the breakout mode is not known for all platforms and hard to maintain. Maybe we can relax that in the Yang model file, and we validate that by the sonic-utilities or other plugins (which was the case already). The yang model here is still good to have at least to validate the sanity of field name etc. This also makes the table to be consistent with other tables.

@zhenggen-xu : I guess then , it makes sense to go ahead by just removing the pattern in this yang model and we can still keep the yang model file. 
```
                leaf brkout_mode {
                    type string {
                        length 1..64;
                        /*
                         * Below allowed patterns are based on most used Platforms,
                         * Add any other breakout-mode to allow Dynamic Port
                         * Breakout to that breakout-mode.
                         */
                        pattern '1x100G\[40G\]|2x50G|4x25G\[10G\]|2x25G\(2\)\+1x50G\(2\)|1x50G\(2\)\+2x25G\(2\)|1x400G|2x200G|4x100G|8x50G|1x200G\[100G,50G,40G,25G,10G,1G\]|2x100G\[50G,40G,25G,10G,1G\]|4x50G\[40G,25G,10G,1G\]|1x25G\[10G\]|1x100G\[50G,40G,25G,10G\]|2x50G\[40G,25G,10G\]|4x25G\[10G\]|1x25G\[10G,1G\]|1x100G\[50G,40G,25G,10G,1G\]|2x50G\[40G,25G,10G,1G\]|4x25G\[10G,1G\]|1x400G\[200G,100G,50G,40G,25G,10G,1G\]|2x200G\[100G,50G,40G,25G,10G,1G\]|4x100G\[50G,40G,25G,10G,1G\]';
                    }
                }
```

2021-05-13 05:05 UTC, zhenggen-xu commented
> > After some more thought, I think we don't want to treat this table BREAKOUT_CFG very differently. The main problem for this table with Yang models is that the breakout mode is not known for all platforms and hard to maintain. Maybe we can relax that in the Yang model file, and we validate that by the sonic-utilities or other plugins (which was the case already). The yang model here is still good to have at least to validate the sanity of field name etc. This also makes the table to be consistent with other tables.
> 
> @zhenggen-xu : I guess then , it makes sense to go ahead by just removing the pattern in this yang model and we can still keep the yang model file.
> 
> ```
>                 leaf brkout_mode {
>                     type string {
>                         length 1..64;
>                         /*
>                          * Below allowed patterns are based on most used Platforms,
>                          * Add any other breakout-mode to allow Dynamic Port
>                          * Breakout to that breakout-mode.
>                          */
>                         pattern '1x100G\[40G\]|2x50G|4x25G\[10G\]|2x25G\(2\)\+1x50G\(2\)|1x50G\(2\)\+2x25G\(2\)|1x400G|2x200G|4x100G|8x50G|1x200G\[100G,50G,40G,25G,10G,1G\]|2x100G\[50G,40G,25G,10G,1G\]|4x50G\[40G,25G,10G,1G\]|1x25G\[10G\]|1x100G\[50G,40G,25G,10G\]|2x50G\[40G,25G,10G\]|4x25G\[10G\]|1x25G\[10G,1G\]|1x100G\[50G,40G,25G,10G,1G\]|2x50G\[40G,25G,10G,1G\]|4x25G\[10G,1G\]|1x400G\[200G,100G,50G,40G,25G,10G,1G\]|2x200G\[100G,50G,40G,25G,10G,1G\]|4x100G\[50G,40G,25G,10G,1G\]';
>                     }
>                 }
> ```

Yes, let's keep the file, but not maintain the pattern here, the pattern validation is done by platform specific platform.json and library.

2021-06-10 17:42 UTC, anshuv-mfst commented
@praveen-li - can you please address review comments and close on open items.

2021-07-29 00:58 UTC, praveen-li commented
/azp run

2021-09-02 17:33 UTC, venkatmahalingam commented on src/sonic-yang-models/yang-models/sonic-breakout_cfg.yang
> +                    description "break_mode for port, it is verifed using platform.json";
Please fix the typo.

2021-09-02 17:35 UTC, zhangyanzhao commented
@zhenggen-xu  will take a second approval, then merge by Guohan.

2021-09-02 17:36 UTC, dgsudharsan approved these changes

2021-09-10 16:17 UTC, zhangyanzhao commented
@lguohan can you please merge this PR? Thanks.

2021-09-30 17:05 UTC, lguohan commented
/azp run

2021-09-30 17:06 UTC, zhenggen-xu approved these changes

2021-09-30 17:31 UTC, zhangyanzhao commented
will merge after the test passed

2021-09-30 17:34 UTC, praveen-li commented
/apzw run

2021-10-21 17:06 UTC, zhangyanzhao commented
azpw /run

2021-11-01 15:25 UTC, lguohan approved these changes

2021-11-01 15:26 UTC, merged