Invoking python3 installation for PDDF 2.0 PAI package
Azure/sonic-buildimage pull request #7100
Opened 2021-03-19 01:03 UTC by fk410167

#### Why I did it
2.0 Platform APIs python3 wheel package should get installed on the HOST as well as PMON docker

#### How I did it
Adjusting the PDDF utility with python3 commands

#### How to verify it
Check for the python3 package installation on a PDDF supported platform

```
root@sonic:/home/admin#
root@sonic:/home/admin# pip3 show sonic-platform
Name: sonic-platform
Version: 1.0
Summary: SONiC platform API implementation on Accton Platforms
Home-page: https://github.com/Azure/sonic-buildimage
Author: SONiC Team
Author-email: linuxnetdev@microsoft.com
License: Apache 2.0
Location: /usr/local/lib/python3.7/dist-packages
Requires:
Required-by:
root@sonic:/home/admin# python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sonic_platform
>>> ch = sonic_platform.platform.Platform().get_chassis()
>>>
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

#### Description for the changelog

#### A picture of a cute animal (not mandatory but encouraged)

2021-03-19 05:14 UTC, fk410167 commented
retest please

2021-03-19 09:39 UTC, fk410167 commented
retest this please

2021-03-19 16:19 UTC, fk410167 commented
retest this please

2021-03-19 16:48 UTC, fk410167 commented
retest this please

2021-03-20 03:09 UTC, fk410167 commented
retest this please

2021-03-21 03:37 UTC, fk410167 commented
retest this please

2021-03-21 03:37 UTC, fk410167 commented
@jleveque 
Can you review and merge this?

2021-03-22 03:18 UTC, fk410167 commented
retest please

2021-03-29 08:34 UTC, fk410167 commented
retest this please

2021-04-02 13:48 UTC, fk410167 commented
retest this please

2021-04-05 16:05 UTC, jleveque requested changes

2021-04-05 16:05 UTC, jleveque commented on platform/pddf/i2c/utils/pddf_util.py
> +                print("Error: Unable to uninstall the sonic-platform whl pkg from pmon container.\)
LGTM caught this syntax error. Closing parenthesis should be placed at the end of the next line and the backslash can be removed.

2021-04-05 17:38 UTC, jleveque approved these changes

2021-04-08 04:15 UTC, fk410167 commented
@jleveque 

Can you merge this please?

2021-04-08 15:21 UTC, merged