[as7326-56x] Add to support PDDF
Azure/sonic-buildimage pull request #7176
Opened 2021-03-29 08:18 UTC by jostar-yang

Signed-off-by: Jostar Yang <jostar_yang@accton.com.tw>

#### Why I did it
Add to support PDDF.
#### How I did it
Implement pddff related code.
#### How to verify it
Test pddf cmd, sfputil , sensors.
root@sonic:~# pddf_psuutil seninfo
PSU1 is Not OK

PSU2 is OK
Output Voltage: 12062.0 mv
Output Current: 17000.0 ma
Output Power: 206000.0 mw
Fan1 Speed: 6144 rpm

root@sonic:~#
root@sonic:~# pddf_psuutil mfrinfo
PSU1 is Not OK

PSU2 is OK
Manufacture Id: ACBEL
Model: FSF019
Serial Number: FSF0191813105530
Fan Direction: Exhaust

root@sonic:~#
root@sonic:~# pddf_psuutil status
PSU    Status
-----  --------
PSU1   NOT OK
PSU2   OK
root@sonic:~# sensors

fan_ctrl-i2c-11-66
Adapter: i2c-1-mux (chan_id 2)
fan1:        23200 RPM
fan2:        19200 RPM
fan3:        23400 RPM
fan4:        19500 RPM
fan5:        24000 RPM
fan6:        19600 RPM
fan7:           0 RPM
fan8:           0 RPM
fan9:        22500 RPM
fan10:       19600 RPM
fan11:       23300 RPM
fan12:       19300 RPM

pch_haswell-virtual-0
Adapter: Virtual device
temp1:        +36.5 C

psu_pmbus-i2c-17-59
Adapter: i2c-1-mux (chan_id 0)
in3:          +0.00 V
fan1:           0 RPM
power2:        0.00 W
curr2:        +0.00 A

lm75-i2c-15-4a
Adapter: i2c-1-mux (chan_id 6)
temp1:        +26.0 C  (high = +80.0 C, hyst = +75.0 C)

lm75-i2c-15-48
Adapter: i2c-1-mux (chan_id 6)
temp1:        +31.0 C  (high = +80.0 C, hyst = +75.0 C)

psu_pmbus-i2c-13-5b
Adapter: i2c-1-mux (chan_id 4)
in3:         +12.06 V
fan1:        6144 RPM
power2:      241.00 W
curr2:       +21.00 A

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +40.0 C  (high = +82.0 C, crit = +104.0 C)
Core 0:         +40.0 C  (high = +82.0 C, crit = +104.0 C)
Core 1:         +40.0 C  (high = +82.0 C, crit = +104.0 C)
Core 2:         +40.0 C  (high = +82.0 C, crit = +104.0 C)
Core 3:         +40.0 C  (high = +82.0 C, crit = +104.0 C)

lm75-i2c-15-4b
Adapter: i2c-1-mux (chan_id 6)
temp1:        +26.0 C  (high = +80.0 C, hyst = +75.0 C)

lm75-i2c-15-49
Adapter: i2c-1-mux (chan_id 6)
temp1:        +29.5 C  (high = +80.0 C, hyst = +75.0 C)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

#### Description for the changelog

#### A picture of a cute animal (not mandatory but encouraged)

2021-04-01 15:16 UTC, fk410167 approved these changes

2021-04-14 21:36 UTC, jleveque requested changes

2021-04-14 21:36 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform_setup.py
> +        'Programming Language :: Python :: 2.7',
Should read `'Programming Language :: Python :: 3.7',`

2021-04-14 21:37 UTC, jleveque requested changes

2021-04-14 21:37 UTC, jleveque commented on platform/broadcom/sonic-platform-modules-accton/as7326-56x/sonic_platform_setup.py
> +        'Programming Language :: Python :: 2.7',
Should read `'Programming Language :: Python :: 3.7',`

2021-04-15 16:38 UTC, jleveque approved these changes

2021-04-15 16:39 UTC, merged