Fix vtysh shell-ingestion security issue
Azure/sonic-buildimage pull request #7759
Opened 2021-05-31 05:44 UTC by xumia

#### Why I did it
Fix vtysh shell-ingestion security issue
Only expose the limited parameters of the vtysh show.

#### How I did it

#### How to verify it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

#### Description for the changelog

#### A picture of a cute animal (not mandatory but encouraged)

2021-05-31 10:48 UTC, qiluo-msft requested changes
Offline discussed.

2021-06-21 06:11 UTC, qiluo-msft approved these changes

2021-06-21 06:49 UTC, xumia commented
@yxieca , could you please help review the PR?

2021-06-22 17:48 UTC, yxieca approved these changes

2021-06-28 01:57 UTC, merged

2021-06-28 02:45 UTC, xumia commented
@qiluo-msft , request to merge the PR to 202012 branch