[201911] [Innovium] Update Cameo & Wistron Drivers
Azure/sonic-buildimage pull request #7855
Opened 2021-06-11 23:09 UTC by shihjeff

#### Why I did it

Update Innovium configs on Cameo and Wistron platforms

#### How I did it

NA

#### How to verify it

Sonic PTF

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

#### Description for the changelog

Update Innovium configs + Add new platforms supporting Innovium chips

#### A picture of a cute animal (not mandatory but encouraged)

2021-06-14 14:57 UTC, lguohan commented
please fix lgtm alerts.

2021-06-16 01:30 UTC, shihjeff commented
> please fix lgtm alerts.

@lguohan All LGTM alerts fixed (except the wrong # arguments false alarms).  Please merge.

2021-06-17 16:59 UTC, jleveque requested changes
You are attempting to check in a shared library binary (device/wistron/x86_64-wistron_sw_to3200k-r0/lib_ivm_serdes_pltfm.so). Rather than checking in the binary, please check in the source and build the shared library when building your platform modules.

2021-06-17 17:18 UTC, shihjeff commented
> You are attempting to check in a shared library binary (device/wistron/x86_64-wistron_sw_to3200k-r0/lib_ivm_serdes_pltfm.so). Rather than checking in the binary, please check in the source and build the shared library when building your platform modules.

@jleveque - unfortunately, this code currently is proprietary and can't be released at this time.  This is for managing the serdes settings on this platform only.

2021-06-17 23:38 UTC, jleveque requested changes

2021-06-17 23:38 UTC, jleveque commented on platform/innovium/sonic-platform-modules-cameo/debian/cameo_platform_version.sh
> +PLATFROM=$1
Typo. Should be "PLATFORM"

2021-06-17 23:38 UTC, jleveque commented on platform/innovium/sonic-platform-modules-cameo/debian/cameo_platform_version.sh
> +PLATFROM_PATH=$2
Typo. Should be "PLATFORM_PATH"

2021-06-17 23:39 UTC, jleveque commented
I noticed there are also `.pyc` files (compiled Python files), which are binary. These should be removed, as well.

2021-07-09 15:24 UTC, shihjeff commented
@jleveque - Changes to remove the *.pyc files are done.  Converted to source code.  Appreciate your time.  Thanks!

CC @Hanly-Cameo

2021-07-21 15:49 UTC, lguohan approved these changes

2021-07-21 16:07 UTC, abdosi approved these changes

2021-07-21 16:09 UTC, merged