[Mellanox - SAI] Split bug fix - Init port auto neg to default on static (SAI XML) port split for 2nd+ port
Azure/sonic-buildimage pull request #7952
Opened 2021-06-23 13:21 UTC by shlomibitton

Split bug fix
Init port auto neg to default on static (SAI XML) port split for 2nd+ port

Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

#### Why I did it

Fix a bug for Mellanox SAI
Init port auto neg to default on static (SAI XML) port split for 2nd+ port

#### How I did it

Update submodule hash pointer.

#### How to verify it

Build an image with the PR.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

#### Description for the changelog

#### A picture of a cute animal (not mandatory but encouraged)

2021-06-23 17:33 UTC, liat-grozovik requested changes
i would like to double check first if this is the right change for this branch. hold on with the merge pls.

2021-06-23 17:39 UTC, liat-grozovik approved these changes

2021-06-24 16:21 UTC, merged

2021-06-24 16:22 UTC, lguohan commented
is this needed for 202012?

2021-06-24 17:58 UTC, liat-grozovik commented
No
There is a different  sai version in 202012.
There is a different PR with relevant changes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: lguohan ***@***.***>
Sent: Thursday, June 24, 2021 7:22:16 PM
To: Azure/sonic-buildimage ***@***.***>
Cc: Liat Grozovik ***@***.***>; Comment ***@***.***>
Subject: Re: [Azure/sonic-buildimage] [Mellanox] advance SAI submodule (#7952)


is this needed for 202012?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/Azure/sonic-buildimage/pull/7952#issuecomment-867775789>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AKTABA2BP4L3P3YYVIO75NDTUNLTRANCNFSM47FZNNQA>.