[multiasic][voq][bgpconf] Fix for the issue of same BGP router id in all asics
Azure/sonic-buildimage pull request #8049
Opened 2021-07-02 21:46 UTC by vganesan-nokia

#### Why I did it

For multiasic, the back end asics use ip addresss of Loopback4096 for BGP router id. In VOQ multi-asic chassis there are no back end asics. All the asics are front end and the iBGP connections are established via Ethernet-IB of asics. Since these asics are not designated as BackEnd, the ip address of interface Loopback0 is used as BGP router id. Since the ip address of Loopback0 is same for all the asics, same router id is used for voq iBGP configurations and hence the iBGP connections are not established. Changes are done to fix this

#### How I did it

To fix this (i.e., to have different router ids for differen iBGP peers), we need to use the ip address of Loopback4096 for
the front end asics also in multi-asic VOQ systems. The bgp main configuration template is adjusted to take ip address of Loopback4096 as router id for asics in multi-asic voq systems irrespective of whether the asic is front end or not.

#### How to verify it

- In  multi-asic voq chassis system have the following in the config_db.json of multiple asics
- Configure different IP addresses for Loopback4096 loop back interface in different asics
- Configure BGP_VOQ_CHASSIS_NEIGHBORS for the Ethernet-IB interfaces.
- Reboot the chassis
- Observe that all iBGP sessions are established state.

2021-07-13 17:02 UTC, abdosi requested changes
please add unit-test case to address template changes

2021-07-23 21:48 UTC, vganesan-nokia commented
> please add unit-test case to address template changes

Added unit tests.

2021-07-26 18:46 UTC, abdosi approved these changes

2021-07-26 19:46 UTC, arlakshm approved these changes

2021-07-26 19:54 UTC, merged