[voq][minigraph] Add admin_status attribute for inband interface
Azure/sonic-buildimage pull request #8050
Opened 2021-07-02 22:29 UTC by vganesan-nokia

#### Why I did it

In the config_db.json generated by minigraph "admin_status" attribute is missing for the VOQ inband interface port in the PORT table.

#### How I did it

Changes done to add admin_status attribute for voq inband interface port, if it exists in the PORT table keys.

#### How to verify it

- For VOQ chassis system, generate config_db.json using minigraph.
- Copy this config_db.json in /etc/sonic/
- Reboot the chassis with this configuration
- The inband interface is operationally up and iBGP sessions are established 

#### Description for the changelog

admin_status attribute for inband interface port

2021-07-07 16:15 UTC, anshuv-mfst commented
@mlorrillere- could you please review, thanks!

2021-07-12 23:35 UTC, mlorrillere submitted a review, later dismissed

2021-07-13 17:06 UTC, abdosi approved these changes

2021-07-13 17:07 UTC, abdosi requested changes
lets add unit test case to cover inband port status

2021-07-26 15:48 UTC, vganesan-nokia commented
> lets add unit test case to cover inband port status

Added unit tests.

2021-07-26 18:32 UTC, merged