[Mellanox] Update SDK\FW ver. 4.4.3216\2008.3218
Azure/sonic-buildimage pull request #8056
Opened 2021-07-04 13:05 UTC by dprital

Signed-off-by: Dror Prital <drorp@nvidia.com>

#### Why I did it

**Changes and new features:**

* Added support in SN4600C systems for new module Finisar ET7402-CWDM4 (100G CWDM4 QSFP28 1310nm SM 2KM).
* Added support for new module MMS1W50-HM (2km transceiver FR4) for 200GbE
* Improved performance of "per-port-buffer" counters
* Added support for Kernel 5.10

**Bugs fixes:**

* On rare occasions (0.5%), in SN4600C systems, when using 100GbE NRZ mode and Fastboot flow, the link up time may take up to 10 seconds
* 50G/100G links that are operationally down before warm-reboot are not coming up after warm-reboot
* 50G/100G links with admin shut / no shut commands are not coming up after warm-reboot
#### How I did it

#### How to verify it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [X] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

#### Description for the changelog

#### A picture of a cute animal (not mandatory but encouraged)

2021-07-04 13:08 UTC, liat-grozovik requested changes

2021-07-04 13:08 UTC, liat-grozovik commented on platform/mellanox/fw.mk
> +MLNX_SPC_FW_VERSION = 13.2008.32180
wrong FW version. please fix

2021-07-04 13:16 UTC, dprital commented on platform/mellanox/fw.mk
> +MLNX_SPC_FW_VERSION = 13.2008.32180
Fixed. Thanks!

2021-07-04 13:22 UTC, liat-grozovik approved these changes

2021-07-06 04:31 UTC, merged

2021-07-09 15:55 UTC, abdosi commented
@liat-grozovik and @dprital  these PR is conflicting for 201911. Please create one for 201911.

cc @prsunny

2021-07-09 16:16 UTC, prsunny commented
@dprital , @liat-grozovik , could you please raise the PR today, we would need to start the build asap.

2021-07-10 00:02 UTC, dgsudharsan commented
@prsunny The pull request is raised here. Can you please reivew? https://github.com/Azure/sonic-buildimage/pull/8145