Addhwsku
Azure/sonic-buildimage pull request #8372
Opened 2021-08-07 20:08 UTC by carl-nokia

#### Why I did it
hwsku.json port_type attribute is the preferred method for test to differentiate copper vs sfp+ for Nokia-7215.
#### How I did it
added PR 8370 on which this PR depends first -  then added hwsku.json file according to platform specification. 
#### How to verify it

#### Which release branch to backport (provide reason below if selected)
Depends on PR 8370 

Needed for Nokia 7215 test pass
- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [ ] 202106

#### Description for the changelog

#### A picture of a cute animal (not mandatory but encouraged)

2021-08-07 21:09 UTC, yxieca approved these changes

2021-08-10 17:58 UTC, dflynn-Nokia commented
/azp run

2021-08-10 18:06 UTC, dflynn-Nokia commented
/AzurePipelines run

2021-08-11 02:58 UTC, Blueve commented
/azp run

2021-08-11 03:15 UTC, Blueve requested changes
Is anywhere consume this attribute? Is yes, you might need update the hwsku_json_checker in your PR as well

2021-08-11 03:15 UTC, Blueve commented on device/nokia/armhf-nokia_ixs7215_52x-r0/Nokia-7215/hwsku.json
> +            "port_type": "RJ45"
This attribute failed to pass this check during build: https://github.com/Azure/sonic-buildimage/blob/e5c2937faec615367a04075ab1a4dc7aeeee1be2/src/sonic-device-data/tests/hwsku_json_checker

2021-08-11 10:27 UTC, Blueve approved these changes

2021-08-12 04:11 UTC, yxieca approved these changes

2021-08-12 07:41 UTC, merged